name: mousai
base: core24 
adopt-info: mousai
grade: stable 
confinement: strict 
license: GPL-3.0
source-code: https://github.com/SeaDve/Mousai
website: https://github.com/soumyaDghosh/mousai-snap
issues: https://github.com/soumyaDghosh/mousai-snap/issues
compression: lzo

lint:
  ignore:
    - classic
    - library

platforms:
  amd64:
  arm64:
  armhf:

parts:
  rustup:
    plugin: rust
    source: .
    rust-channel: "1.79"
    override-build: ""
    override-prime: ""

  mousai:
    after: [ rustup ]
    plugin: meson
    source: https://github.com/SeaDve/Mousai.git
    source-tag: 'v0.7.8'
    source-depth: 1
    build-environment:
      - PATH: ${HOME}/.cargo/bin:${PATH}
      - CARGO_BUILD_JOBS: ${CRAFT_PARALLEL_BUILD_COUNT}
    meson-parameters:
      - --prefix=/snap/mousai/current/usr
    override-pull: |
      craftctl default
      sed -i 's|new(APP_ID,|new("Mousai",|' ${CRAFT_PART_SRC}/src/player.rs
      sed -i 's|https://github.com/SeaDve/Mousai/issues|https://github.com/soumyaDghosh/mousai-snap/issues|g' ${CRAFT_PART_SRC}/src/about.rs
      sed -i 's|https://github.com/SeaDve/Mousai/discussions|https://github.com/soumyaDghosh/mousai-snap/issues|g' ${CRAFT_PART_SRC}/src/about.rs
    build-packages:
      - libssl-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-bad1.0-dev
    organize:
      snap/mousai/current: .
    prime:
      - -snap/mousai
    parse-info: [ usr/share/metainfo/io.github.seadve.Mousai.metainfo.xml ]

  deps:
    after: [mousai]
    plugin: nil
    stage-packages:
      - gstreamer1.0-plugins-bad
    prime:
      - -etc
      - -lib
      - -usr/include
      - -usr/libexec
      - -usr/lib/s*
      - -usr/lib/X11
      - -usr/share

  cleanup:
    after:
      - deps
      - rustup
    plugin: nil
    build-snaps:
      - gnome-46-2404
      - core24
      - ffmpeg-2404
    override-prime: |
      craftctl default
      for snap in "core24" "gnome-46-2404" "ffmpeg-2404"; do
        cd /snap/$snap/current && find . -type f,l -exec rm -rf "$CRAFT_PRIME/{}" \;
      done

plugs:
  ffmpeg-2404:
    interface: content
    target: ffmpeg-platform
    default-provider: ffmpeg-2404


slots:
  mousai:
    interface: dbus
    bus: session
    name: io.github.seadve.Mousai
  mousai-mpris:
    interface: mpris
    name: Mousai


apps:
  mousai:
    command: usr/bin/mousai
    extensions: [ gnome ]
    common-id: io.github.seadve.Mousai
    environment:
      PATH: $SNAP/ffmpeg-platform/usr/bin:$PATH
      LD_LIBRARY_PATH: $SNAP/ffmpeg-platform/usr/lib/$CRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH:$GI_TYPELIB_PATH:$GST_PLUGIN_PATH:$LIBGL_DRIVERS_PATH
    plugs:
      - network
      - network-bind
      - network-status
      - audio-playback
