name: mousai
base: core22 
adopt-info: mousai
grade: stable 
confinement: strict 
license: GPL-3.0
source-code: https://github.com/SeaDve/Mousai
website: https://github.com/soumyaDghosh/mousai-snap
issues: https://github.com/soumyaDghosh/mousai-snap/issues

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

parts:
  rustup:
    plugin: nil
    build-packages: [wget]
    build-environment:
      - RUSTUP_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    override-pull: |
      wget https://sh.rustup.rs -O $CRAFT_PART_SRC/rustup-init.sh
      chmod +x $CRAFT_PART_SRC/rustup-init.sh
    override-build: |
      $CRAFT_PART_SRC/rustup-init.sh -y --no-modify-path
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      for i in `ls $RUSTUP_HOME/bin/`; do
        ln -s ../share/rust/bin/$i $CRAFT_PART_INSTALL/usr/bin/$i
      done
    override-prime: |
      echo 'Skip Prime'
  mousai:
    after: [ rustup ]
    plugin: meson
    source: https://github.com/SeaDve/Mousai.git
    source-tag: 'v0.7.5'
    source-depth: 1
    build-environment:
      - RUSTUP_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    meson-parameters:
      - --prefix=/snap/mousai/current/usr
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/mousai.patch
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp -r $CRAFT_PART_INSTALL/snap/mousai/current/usr/share/icons $CRAFT_PART_INSTALL/meta/gui/
      for i in `find $CRAFT_PART_INSTALL/meta/gui/icons -name "*.svg" -o -name "*.png"`; do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      done
    build-packages:
      - libssl-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-bad1.0-dev
    organize:
      snap/mousai/current: .
    prime:
      - -snap/mousai
    parse-info: [ usr/share/metainfo/io.github.seadve.Mousai.metainfo.xml ]
  deps:
    plugin: nil
    stage-packages:
      - gstreamer1.0-plugins-bad
    prime:
      - usr/lib/*/gstreamer-1.0/libgstaccurip.so
      - usr/lib/*/gstreamer-1.0/libgstadpcmdec.so
      - usr/lib/*/gstreamer-1.0/libgstadpcmenc.so
      - usr/lib/*/gstreamer-1.0/libgstaes.so
      - usr/lib/*/gstreamer-1.0/libgstaiff.so
      - usr/lib/*/gstreamer-1.0/libgstaom.so
      - usr/lib/*/gstreamer-1.0/libgstasfmux.so
      - usr/lib/*/gstreamer-1.0/libgstassrender.so
      - usr/lib/*/gstreamer-1.0/libgstaudiobuffersplit.so
      - usr/lib/*/gstreamer-1.0/libgstaudiofxbad.so
      - usr/lib/*/gstreamer-1.0/libgstaudiolatency.so
      - usr/lib/*/gstreamer-1.0/libgstaudiomixmatrix.so
      - usr/lib/*/gstreamer-1.0/libgstaudiovisualizers.so
      - usr/lib/*/gstreamer-1.0/libgstautoconvert.so
      - usr/lib/*/gstreamer-1.0/libgstbayer.so
      - usr/lib/*/gstreamer-1.0/libgstbluez.so
      - usr/lib/*/gstreamer-1.0/libgstbs2b.so
      - usr/lib/*/gstreamer-1.0/libgstbz2.so
      - usr/lib/*/gstreamer-1.0/libgstchromaprint.so
      - usr/lib/*/gstreamer-1.0/libgstclosedcaption.so
      - usr/lib/*/gstreamer-1.0/libgstcodecalpha.so
      - usr/lib/*/gstreamer-1.0/libgstcoloreffects.so
      - usr/lib/*/gstreamer-1.0/libgstcolormanagement.so
      - usr/lib/*/gstreamer-1.0/libgstcurl.so
      - usr/lib/*/gstreamer-1.0/libgstdash.so
      - usr/lib/*/gstreamer-1.0/libgstdc1394.so
      - usr/lib/*/gstreamer-1.0/libgstde265.so
      - usr/lib/*/gstreamer-1.0/libgstdebugutilsbad.so
      - usr/lib/*/gstreamer-1.0/libgstdecklink.so
      - usr/lib/*/gstreamer-1.0/libgstdtls.so
      - usr/lib/*/gstreamer-1.0/libgstdtsdec.so
      - usr/lib/*/gstreamer-1.0/libgstdvb.so
      - usr/lib/*/gstreamer-1.0/libgstdvbsubenc.so
      - usr/lib/*/gstreamer-1.0/libgstdvbsuboverlay.so
      - usr/lib/*/gstreamer-1.0/libgstdvdspu.so
      - usr/lib/*/gstreamer-1.0/libgstfaad.so
      - usr/lib/*/gstreamer-1.0/libgstfaceoverlay.so
      - usr/lib/*/gstreamer-1.0/libgstfbdevsink.so
      - usr/lib/*/gstreamer-1.0/libgstfestival.so
      - usr/lib/*/gstreamer-1.0/libgstfieldanalysis.so
      - usr/lib/*/gstreamer-1.0/libgstflite.so
      - usr/lib/*/gstreamer-1.0/libgstfluidsynthmidi.so
      - usr/lib/*/gstreamer-1.0/libgstfreeverb.so
      - usr/lib/*/gstreamer-1.0/libgstfrei0r.so
      - usr/lib/*/gstreamer-1.0/libgstgaudieffects.so
      - usr/lib/*/gstreamer-1.0/libgstgdp.so
      - usr/lib/*/gstreamer-1.0/libgstgeometrictransform.so
      - usr/lib/*/gstreamer-1.0/libgstgme.so
      - usr/lib/*/gstreamer-1.0/libgstgsm.so
      - usr/lib/*/gstreamer-1.0/libgsthls.so
      - usr/lib/*/gstreamer-1.0/libgstid3tag.so
      - usr/lib/*/gstreamer-1.0/libgstinter.so
      - usr/lib/*/gstreamer-1.0/libgstinterlace.so
      - usr/lib/*/gstreamer-1.0/libgstipcpipeline.so
      - usr/lib/*/gstreamer-1.0/libgstivfparse.so
      - usr/lib/*/gstreamer-1.0/libgstivtc.so
      - usr/lib/*/gstreamer-1.0/libgstjp2kdecimator.so
      - usr/lib/*/gstreamer-1.0/libgstkate.so
      - usr/lib/*/gstreamer-1.0/libgstkms.so
      - usr/lib/*/gstreamer-1.0/libgstladspa.so
      - usr/lib/*/gstreamer-1.0/libgstldac.so
      - usr/lib/*/gstreamer-1.0/libgstlegacyrawparse.so
      - usr/lib/*/gstreamer-1.0/libgstlv2.so
      - usr/lib/*/gstreamer-1.0/libgstmidi.so
      - usr/lib/*/gstreamer-1.0/libgstmodplug.so
      - usr/lib/*/gstreamer-1.0/libgstmpeg2enc.so
      - usr/lib/*/gstreamer-1.0/libgstmpegpsdemux.so
      - usr/lib/*/gstreamer-1.0/libgstmpegpsmux.so
      - usr/lib/*/gstreamer-1.0/libgstmpegtsdemux.so
      - usr/lib/*/gstreamer-1.0/libgstmpegtsmux.so
      - usr/lib/*/gstreamer-1.0/libgstmplex.so
      - usr/lib/*/gstreamer-1.0/libgstmsdk.so
      - usr/lib/*/gstreamer-1.0/libgstmusepack.so
      - usr/lib/*/gstreamer-1.0/libgstmxf.so
      - usr/lib/*/gstreamer-1.0/libgstnetsim.so
      - usr/lib/*/gstreamer-1.0/libgstnvcodec.so
      - usr/lib/*/gstreamer-1.0/libgstopenal.so
      - usr/lib/*/gstreamer-1.0/libgstopenaptx.so
      - usr/lib/*/gstreamer-1.0/libgstopenexr.so
      - usr/lib/*/gstreamer-1.0/libgstopenh264.so
      - usr/lib/*/gstreamer-1.0/libgstopenjpeg.so
      - usr/lib/*/gstreamer-1.0/libgstopenmpt.so
      - usr/lib/*/gstreamer-1.0/libgstopenni2.so
      - usr/lib/*/gstreamer-1.0/libgstopusparse.so
      - usr/lib/*/gstreamer-1.0/libgstpcapparse.so
      - usr/lib/*/gstreamer-1.0/libgstpnm.so
      - usr/lib/*/gstreamer-1.0/libgstproxy.so
      - usr/lib/*/gstreamer-1.0/libgstqroverlay.so
      - usr/lib/*/gstreamer-1.0/libgstremovesilence.so
      - usr/lib/*/gstreamer-1.0/libgstresindvd.so
      - usr/lib/*/gstreamer-1.0/libgstrfbsrc.so
      - usr/lib/*/gstreamer-1.0/libgstrist.so
      - usr/lib/*/gstreamer-1.0/libgstrsvg.so
      - usr/lib/*/gstreamer-1.0/libgstrtmp.so
      - usr/lib/*/gstreamer-1.0/libgstrtmp2.so
      - usr/lib/*/gstreamer-1.0/libgstrtpmanagerbad.so
      - usr/lib/*/gstreamer-1.0/libgstrtponvif.so
      - usr/lib/*/gstreamer-1.0/libgstsbc.so
      - usr/lib/*/gstreamer-1.0/libgstsctp.so
      - usr/lib/*/gstreamer-1.0/libgstsdpelem.so
      - usr/lib/*/gstreamer-1.0/libgstsegmentclip.so
      - usr/lib/*/gstreamer-1.0/libgstshm.so
      - usr/lib/*/gstreamer-1.0/libgstsiren.so
      - usr/lib/*/gstreamer-1.0/libgstsmooth.so
      - usr/lib/*/gstreamer-1.0/libgstsmoothstreaming.so
      - usr/lib/*/gstreamer-1.0/libgstsndfile.so
      - usr/lib/*/gstreamer-1.0/libgstsoundtouch.so
      - usr/lib/*/gstreamer-1.0/libgstspandsp.so
      - usr/lib/*/gstreamer-1.0/libgstspeed.so
      - usr/lib/*/gstreamer-1.0/libgstsrt.so
      - usr/lib/*/gstreamer-1.0/libgstsrtp.so
      - usr/lib/*/gstreamer-1.0/libgstsubenc.so
      - usr/lib/*/gstreamer-1.0/libgstswitchbin.so
      - usr/lib/*/gstreamer-1.0/libgstteletext.so
      - usr/lib/*/gstreamer-1.0/libgsttimecode.so
      - usr/lib/*/gstreamer-1.0/libgsttranscode.so
      - usr/lib/*/gstreamer-1.0/libgstttmlsubs.so
      - usr/lib/*/gstreamer-1.0/libgstuvch264.so
      - usr/lib/*/gstreamer-1.0/libgstv4l2codecs.so
      - usr/lib/*/gstreamer-1.0/libgstva.so
      - usr/lib/*/gstreamer-1.0/libgstvideofiltersbad.so
      - usr/lib/*/gstreamer-1.0/libgstvideoframe_audiolevel.so
      - usr/lib/*/gstreamer-1.0/libgstvideoparsersbad.so
      - usr/lib/*/gstreamer-1.0/libgstvideosignal.so
      - usr/lib/*/gstreamer-1.0/libgstvmnc.so
      - usr/lib/*/gstreamer-1.0/libgstvoaacenc.so
      - usr/lib/*/gstreamer-1.0/libgstvoamrwbenc.so
      - usr/lib/*/gstreamer-1.0/libgstwaylandsink.so
      - usr/lib/*/gstreamer-1.0/libgstwebp.so
      - usr/lib/*/gstreamer-1.0/libgstwebrtc.so
      - usr/lib/*/gstreamer-1.0/libgstwebrtcdsp.so
      - usr/lib/*/gstreamer-1.0/libgstwildmidi.so
      - usr/lib/*/gstreamer-1.0/libgstx265.so
      - usr/lib/*/gstreamer-1.0/libgsty4mdec.so
      - usr/lib/*/gstreamer-1.0/libgstzbar.so
      - usr/lib/*/gstreamer-1.0/libgstzxing.so

slots:
  mousai:
    interface: dbus
    bus: session
    name: io.github.seadve.Mousai
  mousai-mpris:
    interface: mpris
    name: Mousai
apps:
  mousai:
    command: usr/bin/mousai
    extensions: [ gnome ]
    common-id: io.github.seadve.Mousai
    plugs:
      - home
      - network
      - network-bind
      - network-status
      - audio-playback
