name: mousai
base: core22 
adopt-info: mousai
grade: stable 
confinement: strict 
license: GPL-3.0
source-code: https://github.com/SeaDve/Mousai
website: https://github.com/soumyaDghosh/mousai-snap
issues: https://github.com/soumyaDghosh/mousai-snap/issues

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

parts:
  rustup:
    plugin: nil
    build-packages: [wget]
    build-environment:
      - RUSTUP_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    override-pull: |
      wget https://sh.rustup.rs -O $CRAFT_PART_SRC/rustup-init.sh
      chmod +x $CRAFT_PART_SRC/rustup-init.sh
    override-build: |
      $CRAFT_PART_SRC/rustup-init.sh -y --no-modify-path
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      for i in `ls $RUSTUP_HOME/bin/`; do
        ln -s ../share/rust/bin/$i $CRAFT_PART_INSTALL/usr/bin/$i
      done
    override-prime: |
      echo 'Skip Prime'
  mousai:
    after: [ rustup ]
    plugin: meson
    source: https://github.com/SeaDve/Mousai.git
    source-tag: 'v0.7.6'
    source-depth: 1
    build-environment:
      - RUSTUP_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    meson-parameters:
      - --prefix=/snap/mousai/current/usr
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/mousai.patch
      sed -i 's|new(APP_ID,|new("Mousai",|' $CRAFT_PART_SRC/src/player.rs
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp -r $CRAFT_PART_INSTALL/snap/mousai/current/usr/share/icons $CRAFT_PART_INSTALL/meta/gui/
      for i in `find $CRAFT_PART_INSTALL/meta/gui/icons -name "*.svg" -o -name "*.png"`; do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      done
    build-packages:
      - libssl-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-bad1.0-dev
    stage-packages:
      - gstreamer1.0-vaapi
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-plugins-bad
    organize:
      snap/mousai/current: .
    prime:
      - -snap/mousai
    parse-info: [ usr/share/metainfo/io.github.seadve.Mousai.metainfo.xml ]
  cleanup:
    after:
      - mousai
      - rustup
    plugin: nil
    build-snaps:
      - gnome-42-2204
      - core22
      - ffmpeg-2204
    override-prime: |
      craftctl default
      for snap in "core22" "gnome-42-2204" "ffmpeg-2204"; do
        cd /snap/$snap/current && find . -type f,l -exec rm -f "$CRAFT_PRIME/{}" \;
      done

plugs:
  ffmpeg-2204:
    interface: content
    target: ffmpeg-platform
    default-provider: ffmpeg-2204


slots:
  mousai:
    interface: dbus
    bus: session
    name: io.github.seadve.Mousai
  mousai-mpris:
    interface: mpris
    name: Mousai


apps:
  mousai:
    command: usr/bin/mousai
    extensions: [ gnome ]
    common-id: io.github.seadve.Mousai
    environment:
      PATH: $SNAP/ffmpeg-platform/usr/bin:$PATH
      LD_LIBRARY_PATH: $SNAP/ffmpeg-platform/usr/lib/$CRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH:$GI_TYPELIB_PATH:$GST_PLUGIN_PATH:$LIBGL_DRIVERS_PATH
    plugs:
      - network
      - network-bind
      - network-status
      - audio-playback
